export const TorontoCoordinates = {
    latitude: 43.65107,
    longitude: -79.347015
}

export const customCoordinate = {
    latitude: 43.65107,
    longitude: -79.347015
}

export const SystemRole = {
  ADMIN: 'admin',
  FLEET_MANAGER: 'fleet_manager',
  DISPATCHER: 'dispatcher',
  DRIVER: 'driver',
  MAINTENANCE: 'maintenance',
  SALES_MANAGER: 'sales_manager',
  CUSTOMER_SUCCESS: 'customer_success',
  FINANCE: 'finance',
  CUSTOMER: 'customer',
  READ_ONLY: 'read_only',
}

export const systemPlan = {
  FreeTrial: 'free-trial',
  FleetManagement: 'fleet_management',
  SubscriptionRental: 'subscription-rental',
  DispatchCentre: 'dispatch-centre',
  DriverManagement: 'driver-management',
  AIDashcam: 'ai-dashcam',
  AIInspection: 'ai-inspection',
  Maintenance: 'maintenance',
}

export const systemModule = {
  Dashboard: 'dashboard',
  Leads: 'leads',
  Map: 'map',
  MapAIDashCam: 'map_ai-dashcam',
  Fleet: 'fleet',
  FleetSchedules: 'fleet_schedules',
  FleetSchedulesVehicleAssignment: 'fleet_schedules_vehicle-assignment',
  FleetSchedulesMaintenance: 'fleet_schedules_maintenance',
  FleetMaintenance: 'fleet_maintenance',
  FleetInspection: 'fleet_inspection',
  FleetPictures: 'fleet_pictures',
  FleetDocuments: 'fleet_documents',
  FleetLogs: 'fleet_logs',
  FleetNotes: 'fleet_notes',
  Operations: 'operations',
  OperationsGarages: 'operations_garages',
  OperationsUsers: 'operations_users',
  OperationsPlans: 'operations_plans',
  OperationsDrivers: 'operations_drivers',
  OperationsDriversGeneral: 'operations_drivers_general',
  OperationsDriversVehicleAssignment: 'operations_drivers_vehicle-assignment',
  OperationsDriversBehaviourAndAnalytics: 'operations_drivers_behaviour-and-analytics',
  OperationsDriversKeys: 'operations_drivers_keys',
  OperationsScreeningLogs: 'operations_screening-logs',
  OperationsReports: 'operations_reports',
  Customer: 'customer',
  Maintenance: 'maintenance',
  MaintenanceWorkOrder: 'maintenance_work-order',
  MaintenanceAIRecommendations: 'maintenance_ai-recommendations',
  Dispatch: 'dispatch',
  Orders: 'orders',
  Requests: 'requests',
  Bills: 'bills',
  Settings: 'settings',
  SettingsPreference: 'settings_preference',
  SettingsBusinessInformation: 'settings_business-information',
  SettingsCustomerAgreement: 'settings_customer-agreement',
  SettingsInsurance: 'settings_insurance',
  SettingsAPIKeys: 'settings_api-keys',
  SettingsTelemetryDevice: 'settings_telemetry-device',
  SettingsTaxRate: 'settings_tax-rate',
  SettingsGeofences: 'settings_geofences',
  SettingsOperatorLog: 'settings_operator-log',
  SettingsEventsFlag: 'settings_events-flag',
  SettingsSmsEmailTemplate: 'settings_sms-email-template',
  SettingsSmsEmailTemplateGeneral: 'settings_sms-email-template_general',
  SettingsSmsEmailTemplateFleetManagement: 'settings_sms-email-template_fleet-management',
  SettingsSmsEmailTemplateSubscriptionRental: 'settings_sms-email-template_subscription-rental',
  SettingsSmsEmailTemplateDispatchCentre: 'settings_sms-email-template_dispatch-centre',
  // SettingsSuperAdmin: 'settings_super-admin',
  AgentApp: 'agent-app',
  DriverApp: 'driver-app',
  DriverAppSynopss: 'driver-app_Synopss',
  DriverAppInspection: 'driver-app_inspection',
  AssetCareApp: 'asset-care-app',
  SuperAdmin: 'super-admin',
  SuperAdminCustomPlan: 'super-admin_custom-plan',
}
